version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=blogdb
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - blog-network

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: blogdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - blog-network

  node:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5173:5173" # Vite dev server
    command: bash -c "npm install && npm run dev"
    networks:
      - blog-network

volumes:
  dbdata:

networks:
  blog-network:
